### ISSUE TITLE
Make integration tests wait until ongoing run completes. 

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/google-cloud-spanner-hibernate#105]
https://api.travis-ci.org/v3/job/563283738/log.txt

@ChengyuanZhao Do you know what might be causing the tests to be flaky?

**Comment by ChengyuanZhao** [comment]
This happens when two builds are going on at the same time. They're messing with the tables (remember we have a single set of tables and don't recreate them for each test). 

I would bet it's probably the two rapid merges that happened yesterday fixing the ref doc title. @meltsufin

**Comment by meltsufin** [comment]
Ah true. Maybe there is a way to make the second build wait for the previous one to finish, like by checking for existence or non-existence of some flag in the database?

**Comment by ChengyuanZhao** [comment]
@meltsufin sounds like a good idea :). Though I think we may just need to skip running the tests in the waiting build because it wouldn't have enough time (Travis allows 50 minutes if i recall) to wait for the previous and then run its own.

**Comment by meltsufin** [comment]
Well at least we would know that it failed due to timeout and we can re-run.

**Comment by meltsufin** [comment]
Fixed via setting in Travis.
