### ISSUE TITLE
Support Query Hints

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/google-cloud-spanner-hibernate#117]
Need to implement `String getQueryHintString(String query, String hints)` method in the `SpannerDialect`.

**Comment by dzou** [comment]
I have this implemented however this depends on minor change made to the JDBC driver to support prepended query hints; see this: https://github.com/googleapis/google-cloud-java/issues/6540

This describes the route of prepending query hints to a query if it is possible.

The other way to add query hints would be to parse the query string to determine which part of the string that we should add a hint; this would be a much more technical task.

**Comment by meltsufin** [comment]
Decided to not support it at this time.
