### ISSUE TITLE
Latest version has not been published in MavenCentral

### ISSUE THREAD

**Issue by valdemon** [GoogleCloudPlatform/google-cloud-spanner-hibernate#1328]
The latest version there is `3.4.1` - https://mvnrepository.com/artifact/com.google.cloud/google-cloud-spanner-hibernate-dialect.

**Comment by olavloite** [comment]
Thanks for reporting this. We'll take a look right away.

**Comment by olavloite** [comment]
@valdemon  The missing versions have been pushed to Maven Central. Again thanks for reporting this!
