### ISSUE TITLE
Add Micrometer + Stackdriver Monitoring for performance testing

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/google-cloud-spanner-hibernate#138]
See: [micrometer-registry-stackdriver](https://github.com/micrometer-metrics/micrometer/tree/master/implementations/micrometer-registry-stackdriver/src/main/java/io/micrometer/stackdriver)

Follow-up to #137.

**Comment by JoeWang1127** [comment]
close as obsolete
