### ISSUE TITLE
TableExporter support for Collections and UNIQUE indexes 

### ISSUE THREAD

**Issue by ChengyuanZhao** [GoogleCloudPlatform/google-cloud-spanner-hibernate#17]
This may be pretty involved because in CREATE and DROP statements now any associated or interleaved indexes and child tables must also be dropped or created.

**Comment by ChengyuanZhao** [comment]
NOTE: 

In Spanner the UNIQUE constraint does go in the CREATE TABLE statement. 

Instead you create an index on the column you want to be UNIQUE and that index is given the UNIQUE option, which then enforces uniqueness on the column. This is relevant for the OneToMany or ManyToOne relationship.

**Comment by ChengyuanZhao** [comment]
Added collection support.

Unfortunately hibernate chooses the FK column names in the collection table and they are NOT the same as the names in the parent table as required by Spanner. So collection support is without interleaved support.

**Comment by meltsufin** [comment]
Can you point to the code in Hibernate that does it? Is there any way to override it, since interleaved tables are in fact a perfect fit for collections.

**Comment by ChengyuanZhao** [comment]
It looks like this is handled by `org.hibernate.cfg.annotations.CollectionBinder` where the behavior is hard-coded.

**Comment by meltsufin** [comment]
Closing in favor of #140 and #165 .
