### ISSUE TITLE
Replace String Concatenations in the Dialect with StringBuilder

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/google-cloud-spanner-hibernate#182]
String concatenation is used a lot in our dialect, but this can be replaced with usage of StringBuilder which is faster and uses less memory. This is the style of Hibernate core as well, see: https://github.com/hibernate/hibernate-orm/blob/e5dc635a52362f69b69acb8d5b166b69b165dbbd/hibernate-core/src/main/java/org/hibernate/tool/schema/internal/StandardTableExporter.java#L46

**Comment by dmitry-s** [comment]
This might not be necessary, as java optimizer replaces spring concatenation with StringBuilder anyway, unless we concatenate inside a loop:
https://stackoverflow.com/questions/11942368/why-use-stringbuilder-explicitly-if-the-compiler-converts-string-concatenation-t

**Comment by dzou** [comment]
Good point @dmitry-s - closing this.
