### ISSUE TITLE
Create example with @Interleaved

### ISSUE THREAD

**Issue by RysoBeco** [GoogleCloudPlatform/google-cloud-spanner-hibernate#196]
Sample of how to use interleaved entity would be helpful. 
For instance combination of @GeneratedValue, and @Interleaved when creating entries is not obvious

**Comment by dzou** [comment]
Thanks for the report, yes we can implement something for this.

**Comment by dzou** [comment]
@RysoBeco - Created a sample of how to setup the `@Interleaved` annotation in your entity in #197 , this should help; it demonstrates correctly setting up the `@OneToMany` and `@ManyToOne` annotations for your entities.
