### ISSUE TITLE
Fix tests broken by emulator migration.

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/google-cloud-spanner-hibernate#247]
Followup to https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/pull/234

Some tests were broken after the Emulator migration. I think there are some differences in behavior between the emulator and real spanner that we can investigate later.

**Comment by zhumin8** [comment]
Won't fix because:
> Spanner emulator does not have feature parity with the latest changes in Spanner.

Mitigated in #336 by tests against a real Spanner instance nightly.
