### ISSUE TITLE
Hibernate 5.5+ / Spring Boot 2.6.X

### ISSUE THREAD

**Issue by husseyd** [GoogleCloudPlatform/google-cloud-spanner-hibernate#366]
Hi guys,

The latest release lacks some support for Hibernate 5.5+, which locks projects to Spring Boot < 2.6 and thus prevents use of [Spring Cloud GCP >2.0.x][(url](https://github.com/GoogleCloudPlatform/spring-cloud-gcp))

Just an FYI really, you're probably already on it.

**Comment by meltsufin** [comment]
Yes, we're working on it in #364.

**Comment by mpeddada1** [comment]
Closing this issue. Hibernate 5.5+ support has been [released](https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/releases/tag/1.5.3).
