### ISSUE TITLE
Illegal argument on static metamodel field injection for Spanner Array

### ISSUE THREAD

**Issue by lucasoares** [GoogleCloudPlatform/google-cloud-spanner-hibernate#392]
Hello.

My team uses the maven processor to generate our metamodels for each JPA entity with this configuration:
```
      <plugin>
        <groupId>org.bsc.maven</groupId>
        <artifactId>maven-processor-plugin</artifactId>
        <version>4.5</version>
        <executions>
          <execution>
            <id>process</id>
            <goals>
              <goal>process</goal>
            </goals>
            <phase>generate-sources</phase>
            <configuration>
              <processors>
                <processor>org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor</processor>
              </processors>
            </configuration>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-jpamodelgen</artifactId>
            <version>5.4.32.Final</version>
          </dependency>
        </dependencies>
      </plugin>
```

For some reason, if you have a Spanner Array type in any JPA entity this error will be logged on application startup:
```
HHH015007: Illegal argument on static metamodel field injection : br.com.stilingue.smartcare.entities.HiddenConversation_#interactionIds; expected type :  org.hibernate.metamodel.model.domain.internal.SingularAttributeImpl; encountered type : javax.persistence.metamodel.ListAttribute
```

The `HiddenConversation` entity in this case is:

```java
@Data
@Entity
@NoArgsConstructor
@Accessors(chain = true)
@TypeDef(name = "spanner-array", typeClass = SpannerArrayListType.class)
@Table(name = "hidden_conversations")
@IdClass(HiddenConversation.PrimaryKeys.class)
public class HiddenConversation {
  @Data
  @NoArgsConstructor
  @AllArgsConstructor
  public static class PrimaryKeys implements Serializable {
    private String externalConversationId;
    private Long universeId;
  }

  @Id
  @Column(name = "external_conversation_id", nullable = false)
  private String externalConversationId;

  @Id
  @Column(name = "universe_id", nullable = false)
  private Long universeId;

  @Type(type = "spanner-array")
  @Column(name = "interaction_ids", nullable = false)
  private List<String> interactionIds;

  @Type(type = "spanner-array")
  @Column(name = "page_ids", nullable = false)
  private List<String> pageIds;
}
```

The ERROR message is displayed for both list attributes of this class.

Wondering if the metamodel functionality is preserved using spanner-array type.

Thanks.

**Comment by mpeddada1** [comment]
Hi @lucasoares, thanks for filing the issue. Could you provide a bit more information on the following:

1) A stacktrace of the error. It can help us trace where the error is coming from. 
2) The version of `google-cloud-spanner-hibernate` you are currently using.

**Comment by lucasoares** [comment]
> Hi @lucasoares, thanks for filing the issue. Could you provide a bit more information on the following:
> 
> 1. A stacktrace of the error. It can help us trace where the error is coming from.
> 2. The version of `google-cloud-spanner-hibernate` you are currently using.

Hello.

There is no stacktrace. It's an error logging without any stacktrace.

Library version:
```
google-cloud-spanner-hibernate-dialect 1.5.2
```

**Comment by mpeddada1** [comment]
Thanks for the info. I see that you're using `1.5.2`. The latest release (1.5.3) which upgrades Hibernate to version `5.6` is out. Can you try that out and see if it makes a difference?

**Comment by mpeddada1** [comment]
Would be able to provide a small reproducer which can help us look into this in detail and troubleshoot?

**Comment by meltsufin** [comment]
Is this issue related?
https://hibernate.atlassian.net/browse/HHH-11803

**Comment by lucasoares** [comment]
@mpeddada1 I think I was missing something in the configuration.. I revised my maven dependencies and now executing clean install I can't see any ERROR for metamodels running the application.. Yes @meltsufin it is related

Updating the hibernate is the right way to fix it.. Thank you.
