### ISSUE TITLE
Figure out how to run existing Hibernate tests to verify Dialect

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/google-cloud-spanner-hibernate#4]
Hibernate has a set of tests for their dialect here: https://github.com/hibernate/hibernate-orm

Devise a method for running tests against our own Spanner-Hibernate dialect.

**Comment by dzou** [comment]
I have an initial setup here with instructions: https://github.com/dzou/hibernate-orm

At this point, the tests are run against the spanner jdbc driver, but most of the tests are broken.

**Comment by meltsufin** [comment]
Is it possible to have the test execution added to this project without copying the actual tests? Do we need a Gradle setup?

**Comment by dzou** [comment]
I think it should be possible... I will investigate.

**Comment by ChengyuanZhao** [comment]
Obsolete pretty much. The existing tests largely use features we can't support yet. Please see the other open testing issue for integration testing.
