### ISSUE TITLE
How to use pessimistic_write lock with Spanner using JPA/hibernate

### ISSUE THREAD

**Issue by nayanbijagare** [GoogleCloudPlatform/google-cloud-spanner-hibernate#404]
I have a requirement like, whenever employee information is read from employee table, no-one can read/update/delete the the same row information until transaction gets finished, 

I got to know for such purpose "PESSIMISTIC_WRITE" lock is used in JPA.
I tried to use it by using below code but its not holding the lock.
When I try to hit the same query from other instance its giving result

Could you please suggest me any solution for it.

```java
@Repository
public interface EmployeeRepository extends JpaRepository<EmployeeEntity, Integer>  {

@Lock(LockModeType.PESSIMISTIC_WRITE)
	@Query("SELECT c FROM Employee c WHERE c.empId = :empId)
	public EmployeeEnity getEmployee(@Param("empId") Integer empId);
}
}
```

**Comment by meltsufin** [comment]
Cloud Spanner does not support selecting for lock, like select-for-update. We might need to throw an exception when someone tries to use this though.
(@elefeint see [here](https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/blob/master/google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerDialect.java#L378)).

Instead you can try using optimistic locking and/or Spanner read-write transactions, which I believe is the default setting.
cc/ @olavloite

**Comment by nayanbijagare** [comment]
Could you please suggest if there is any provision for "optimistic locking and/or Spanner read-write transactions" in Hibernate/JPA?

**Comment by olavloite** [comment]
> Can we achieve "optimistic locking and/or Spanner read-write transactions" in Hibernate/JPA? if yes then could you please provide any example link if you have.

Note that these two are very different things:
1. Spanner read/write transactions: This will be used automatically for all transactions that you create with JPA. From your example it seems that you are using Spring. Annotating a method with `@Transactional` will make that method automatically start a transaction when it is started.  Here's a tutorial on how to use transactions in general with Spring and JPA: https://www.baeldung.com/transaction-configuration-with-jpa-and-spring
2. Optimistic locking: Optimistic locking is used to ensure that data that was read in one transaction, then stored in memory for a while, and then accessed again in a new transaction has not been edited by any other transaction in the meantime. This feature in JPA is database system independent (that is; you can use it with both Spanner and any other database system). A tutorial for optimistic locking can be found here: https://www.baeldung.com/jpa-optimistic-locking

Your original request, `PESSIMISTIC_WRITE` lock (effectively an exclusive lock on a row), is not supported in Cloud Spanner.

**Comment by mpeddada1** [comment]
Thank you for the additional context, @olavloite!

**Comment by nayanbijagare** [comment]
@olavloite  Thanks for providing me valuable information.
Actually I am having use case like,  I want to generate sequential number and store it into db and the next number should be generated by reading last store number.
ex- suppose100 is stored in db. when new request comes for sequence generation, last inserted value ie; 100 will be read and by referring it 101 will be generated and store into db.

But if multiple requests comes for sequence generation at a time then there is a chance of conflicts.
To handle this scenario I have read some articles and got to know, by using transaction we can achieve this.

Could you please suggest any good solution to handle this scenario with spanner.
I am using Hibernate + spring boot technologies to read and write data into spanner.

**Comment by elefeint** [comment]
Generating sequential IDs like this will be a serious bottleneck in your application, especially if it's a primary key. Consider using UUIDs instead.

If you have to do sequential numbers, using optimistic locking strategies, like @olavloite suggested, is how you would implement such sequential increment.
