### ISSUE TITLE
How to reorder joins in a query?

### ISSUE THREAD

**Issue by rodrigogs** [GoogleCloudPlatform/google-cloud-spanner-hibernate#442]
Hello! I've been using this library in a project where we build queries dynamically, based on a filter that is populated by the users.

That said, we add joins on demand by using Specifications depending on the filter.

Analyzing the generated queries performance we noticed that the join order is absolutely critical. When we move heavy table joins to the end of the query, we get a significant performance boost.

It would not be a huge deal if we were able to reorder the joins using the JPA API, but as far as I know, it is not possible.

Is there a way to do it? Is there an alternative way to improve the performance of the queries?

**Comment by elefeint** [comment]
Looking at [Spring Data Jpa utils](https://github.com/spring-projects/spring-data-jpa/blob/f2e7bddb5aa4610f8a5fcf233e44df66ca2011cb/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/query/QueryUtils.java#L888), it looks to me like the joins will remain in the order in which the specification asks for it to be joined. Are you seeing non-deterministic behavior with the join order?

As a matter of this repository, Cloud Spanner's hibernate dialect does not do anything special for joins; it will generate whatever syntactic bits Hibernate specifically asks for.

**Comment by zhumin8** [comment]
Closing as part of cleanup. Please re-open if it's still relevant
