### ISSUE TITLE
Unsupported Features List

### ISSUE THREAD

**Issue by ChengyuanZhao** [GoogleCloudPlatform/google-cloud-spanner-hibernate#47]
This is a list of features we don't support that I will keep here until we have a place in documentation to put them:

- Simba driver AND new driver don't support jdbc NUMERIC or DECIMAL. This means types like BigDecimal cannot be supported regardless of how we want to store them in Spanner because the driver doesn't even attempt to
- several integration tests use aliases in quotes. This is not supported in Spanner, but is supported in traditional databases (for aliases that have spaces in them)

**Comment by dzou** [comment]
- Spanner does not support the [WHERE ... ANY or WHERE ... ALL clauses](https://www.w3schools.com/sql/sql_any_all.asp).

**Comment by meltsufin** [comment]
@dzou  Have you tried it? Interestingly, `ANY` and `ALL` are [reserved](https://cloud.google.com/spanner/docs/lexical) keywords in Spanner.

**Comment by dzou** [comment]
> @dzou Have you tried it? Interestingly, `ANY` and `ALL` are [reserved](https://cloud.google.com/spanner/docs/lexical) keywords in Spanner.

Yeah, pretty sure it doesn't work. When I try something like:

```
SELECT *
FROM Employee
WHERE name = ANY (SELECT name from Employee)
```

I get error "unexpected keyword ANY".

I suspect they reserved the ANY/ALL keywords because they might expand their features to include it in the future.

**Comment by ChengyuanZhao** [comment]
closing since we're apparently using separate issues for each
