### ISSUE TITLE
SQLExceptions during schema migrations are silently ignored

### ISSUE THREAD

**Issue by olavloite** [GoogleCloudPlatform/google-cloud-spanner-hibernate#470]
The `SpannerSchemaManagementTool` will automatically include the `START BATCH DDL` and `RUN BATCH` statements as auxiliary database objects for each schema migration. This ensures that each migration is executed as a single batch, which improves execution performance, and ensures that the parsing of the entire batch is atomic. This means that if one statement is invalid, the entire batch will be refused and nothing will be executed.

However, Hibernate will [ignore](https://github.com/hibernate/hibernate-orm/blob/0baefce734bed664a20f994ad35b0e0017aca770/hibernate-core/src/main/java/org/hibernate/tool/schema/internal/AbstractSchemaMigrator.java#L289) any `SQLException` that is thrown when executing the create/drop statement for an auxiliary database object. This means that if `RUN BATCH` fails, for example because one of the statements in the batch is invalid, the entire batch will not be executed, but Hibernate will not report any problems.

**Comment by elefeint** [comment]
I wonder if Hibernate 6 dialect is affected by this? 
https://github.com/hibernate/hibernate-orm/blob/0baefce734bed664a20f994ad35b0e0017aca770/hibernate-core/src/main/java/org/hibernate/dialect/SpannerDialect.java
