### ISSUE TITLE
Hibernate always translates SpannerException to JpaSystemException

### ISSUE THREAD

**Issue by sqlboy** [GoogleCloudPlatform/google-cloud-spanner-hibernate#473]
I'm actually not 100% sure if this is the right place for this but, here goes.  I'm using Kotlin, Spring, Hibernate/Spanner and I've run into a problem where no matter what exception Spanner JDBC throws, its always translated into a JpaSystemException by Hibernate.

Basic Project:

- Spring Boot 2.7
- Hibernate Dialect: 2.53
- Spanner JDBC: 2.7.11
- Spanner: 6.31.2

Config:

`  datasource:
    driver-class-name: com.google.cloud.spanner.jdbc.JdbcDriver
    url: jdbc:cloudspanner:/projects/PROJECT/instances/INST/databases/DB

  jpa:
    database-platform: com.google.cloud.spanner.hibernate.SpannerDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
`

I'm using a plain old : JpaRepository<T, ID>.  No matter what I do to generate an error (duplicate entry for example) I always get a org.springframework.orm.jpa.JpaSystemException which is thrown by convertHibernateAccessException.  The full cause stack is:

- org.springframework.orm.jpa.JpaSystemException 
- Caused by: org.hibernate.exception.GenericJDBCException
- Caused by: com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory$JdbcSqlExceptionImpl
- Caused by: com.google.cloud.spanner.SpannerException
- Caused by: java.util.concurrent.ExecutionException: com.google.api.gax.rpc.AlreadyExistsException:
- Caused by: com.google.api.gax.rpc.AlreadyExistsException
- Caused by: io.grpc.StatusRuntimeException

In this case what I expect to get is a org.springframework.dao.DuplicateKeyException, or even a com.google.cloud.spanner.SpannerException.  I'm not sure where/how this translation is supposed to happen.  Let me know if you need any more info.

**Comment by emmileaf** [comment]
@sqlboy thank you for reporting this. Given the different layers that seem to be going on in the reported stack trace, would you be able to help provide a small reproducer sample so we can look into this further?

**Comment by meltsufin** [comment]
I don't believe any code in this repo is doing this.
