### ISSUE TITLE
Bring over hibernate ORM integration tests

### ISSUE THREAD

**Issue by ChengyuanZhao** [GoogleCloudPlatform/google-cloud-spanner-hibernate#52]
- [x] https://github.com/hibernate/hibernate-orm/blob/master/documentation/src/test/java/org/hibernate/userguide/sql/SQLTest.java
- [x] https://github.com/hibernate/hibernate-orm/blob/master/documentation/src/test/java/org/hibernate/userguide/hql/HQLTest.java
- [x] https://github.com/hibernate/hibernate-orm/tree/master/documentation/src/test/java/org/hibernate/userguide/inheritance
- [x] https://github.com/hibernate/hibernate-orm/tree/master/documentation/src/test/java/org/hibernate/userguide/fetching
- [x] https://github.com/hibernate/hibernate-orm/tree/master/documentation/src/test/java/org/hibernate/userguide/collections
- [x] https://github.com/hibernate/hibernate-orm/tree/master/documentation/src/test/java/org/hibernate/userguide/persister
- [x] https://github.com/hibernate/hibernate-orm/tree/master/documentation/src/test/java/org/hibernate/userguide/schema
- [x] https://github.com/hibernate/hibernate-orm/tree/master/documentation/src/test/java/org/hibernate/userguide/transactions
- [x] https://github.com/hibernate/hibernate-orm/tree/master/documentation/src/test/java/org/hibernate/userguide/mapping

These are the topics that we could bring over. pick and choose ones to work on @dmitry-s @dzou ?

**Comment by dzou** [comment]
Sure thing, I'll take the HQL Tests

**Comment by ChengyuanZhao** [comment]
I'll take the `collections` test directory

**Comment by ChengyuanZhao** [comment]
@dzou @meltsufin 

Many of the collection-directory tests modify the state of the tables and need to have those tables deleted and recreated and sometimes as tables with the same name but different actual POJO classes...

For those classes that have these issues we will need to go back to what hibernate does (recreate everything after each test)

**Comment by dzou** [comment]
I see. It might be OK since I see that the Collection tests appear to only use 2 entities (like Person + Phone). This means each test would only need to recreate/delete 2 tables which is not too bad. So we can just try to add these tests to the CI and see what effects it has on the run time; if it's not too bad then we can keep.

Maybe if our CI grows to take too long (like taking +12 hours) we can consider something else such as splitting certain sets of tests to be run manual-only.

**Comment by ChengyuanZhao** [comment]
I'll take the `fetching` tests now

**Comment by dzou** [comment]
I'll take `inheritance`

**Comment by ChengyuanZhao** [comment]
`GraphParsingTest.java` from `fetching` is deleted and should be restored when the `graph` set of tests is migrated

**Comment by ChengyuanZhao** [comment]
These tests have all been added and fixed to work.
