### ISSUE TITLE
Dependency compatibility issues as still dialect referring to old hibernate-core package structure. 

### ISSUE THREAD

**Issue by swapy-bhad** [GoogleCloudPlatform/google-cloud-spanner-hibernate#556]
Hello,

This dependency needs to be updated to refer latest hibernate-core jar which recently moved to "org.hibernate.orm"

https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/blob/230de173f5035a1f50072cbad88ef3e7117347f5/google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerServiceContributor.java#L30

![image](https://user-images.githubusercontent.com/125940565/220236304-074dc0a9-0f92-418a-9fd0-fbd3a1813271.png)

![image](https://user-images.githubusercontent.com/125940565/220239533-20684390-e6f6-4aa0-93f2-9d5536f0b457.png)

**Comment by mpeddada1** [comment]
Thanks for filing this issue @swapy-bhad! Please note that this repository only supports Hibernate 5.x. The spanner dialect comes built-in with Hibernate 6.x. See: https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/main/java/org/hibernate/dialect/SpannerDialect.java

**Comment by olavloite** [comment]
@swapy-bhad Version 3.x of this library now supports Hibernate 6.3.
