### ISSUE TITLE
Fix Group BY usage in HQLTests

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/google-cloud-spanner-hibernate#56]
Some Group BY tests in the HQL tests break.

Example: (HQLTest.java:2326)
```
@Test
@Ignore
// Failed to group by entity
public void test_hql_group_by_example_3() {
	doInJPA( this::entityManagerFactory, entityManager -> {
		//tag::hql-group-by-example[]
		//It's even possible to group by entities!
		List<Object[]> personTotalCallDurations = entityManager.createQuery(
				"select p, sum( c.duration ) " +
						"from Call c " +
						"join c.phone ph " +
						"join ph.person p " +
						"group by p", Object[].class )
				.getResultList();
		//end::hql-group-by-example[]
		assertEquals(1, personTotalCallDurations.size());
	});
}
```

**Comment by meltsufin** [comment]
Any ideas as to why?

**Comment by dzou** [comment]
It's due to the "select p" in conjunction with "group by p" not being translated correctly.

Generated SQL query:

```
select person2_.id as col_0_0_, sum(call0_.duration) as col_1_0_, person2_.id as id1_2_, 
person2_.address as address2_2_, person2_.createdOn as createdO3_2_,
person2_.name as name4_2_, person2_.nickName as nickName5_2_, person2_.version as version6_2_ 
from phone_call call0_
inner join Phone phone1_ on call0_.phone_id=phone1_.id
inner join Person person2_ on phone1_.person_id=person2_.id
group by person2_.id
```

Error:
```
java.sql.SQLException: [Simba][SpannerJDBCDriver](100300) Error message from server: INVALID_ARGUMENT: SELECT list expression references person2_.address which is neither grouped nor aggregated [at 1:90]
...duration) as col_1_0_, person2_.id as id1_2_, person2_.address as address2...
                                                 ^
```

**Comment by meltsufin** [comment]
Well the error is accurate, you cannot reference a column in a select that doesn't appear in the group-by. Why does our generated group-by only contain `person2_.id`? How do other dialects solve this problem? It would be exactly the same issue in something like MySQL.

**Comment by dzou** [comment]
Yeah this one is one I believe can be fixed with some investigation.

**Comment by ChengyuanZhao** [comment]
I did some experimenting and the `org.hibernate.dialect.MySQL8Dialect` doesn't do anything different than what we do.

`select s from SubTestEntity s group by s`

translates to `select subtestent0_.id as id1_1_, subtestent0_.id1 as id2_1_, subtestent0_.id2 as id3_1_ from SubTestEntity subtestent0_ group by subtestent0_.id for share`

Note that the "for share" part is unrelated. It's also there if you exclude the "group by s" in the original HQL.

this is the entity btw
```
@Entity
public class SubTestEntity {

  @Id
  String id;

  @ManyToOne
  @JoinColumns({@JoinColumn(name = "id1"), @JoinColumn(name = "id2")})
  TestEntity testEntity;
}
```

**Comment by ChengyuanZhao** [comment]
Some mention I found that MySQL goes against spec to support this:

https://stackoverflow.com/questions/3168042/can-i-use-non-aggregate-columns-with-group-by

**Comment by ChengyuanZhao** [comment]
Also, postgres doesn't do anything with those non-aggregated cols either
`select subtestent0_.id as id1_1_, subtestent0_.id1 as id2_1_, subtestent0_.id2 as id3_1_ from SubTestEntity subtestent0_ group by subtestent0_.id for share of subtestent0_`

**Comment by meltsufin** [comment]
Maybe Oracle is more strict?

**Comment by dzou** [comment]
> Maybe Oracle is more strict?

This probably would not work on Oracle. The test was only enabled for [H2, Postgres, and MySQL](https://github.com/hibernate/hibernate-orm/blob/070c14e1498010024a3fbfb60512fc8d1517f7e3/documentation/src/test/java/org/hibernate/userguide/hql/HQLTest.java#L2349).

**Comment by meltsufin** [comment]
Ah, then we probably don't need to worry about it too much. It seems in fact a feature not supported in Spanner, just like it's not supported in Oracle.
I assume there are other "group by" tests in the suite that actually pass for Spanner.
