### ISSUE TITLE
Unsupported Feature: Alias with quotes

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/google-cloud-spanner-hibernate#58]
Several integration tests use aliases in quotes. This is not supported in Spanner, but is supported in traditional databases (for aliases that have spaces in them).

Parent #47

**Comment by bvandiver** [comment]
Spanner uses backquotes `` for identifier quoting.

**Comment by meltsufin** [comment]
Need to find the test that exercises this and see if we can make it work.

**Comment by JoeWang1127** [comment]
close as not planned
