### ISSUE TITLE
Unsupported Feature: Custom escape char in LIKE expression

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/google-cloud-spanner-hibernate#61]
Spanner does not support LIKE predicates with [custom escape chars](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/like-transact-sql?view=sql-server-2017#pattern-matching-with-the-escape-clause).

Parent #47.

**Comment by meltsufin** [comment]
According to the [docs](https://cloud.google.com/spanner/docs/functions-and-operators#string-functions), you can escape, but not with a custom character.

LIKE | X [NOT] LIKE Y | Checks if the STRING in the first operand X matches a pattern specified by the second operand Y. Expressions can contain these characters:A percent sign "%" matches any number of characters or bytesAn underscore "_" matches a single character or byteYou can escape "\", "_", or "%" using two backslashes. For example, "\\%". If you are using raw strings, only a single backslash is required. For example, r"\%".
-- | -- | --

**Comment by JoeWang1127** [comment]
close as not planned
