### ISSUE TITLE
Spanner does not support namespaced Table annotations

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/google-cloud-spanner-hibernate#77]
Spanner does not support namespace table annotations like this:

```
@Table(
            catalog = "public",
            schema = "store",
            name = "book"
)
```

This produces a fully qualified table name `public.store.book`; however one does not specify tables in Spanner in this way. furthermore it is unclear what concepts the catalog or schema would map to.

**Comment by meltsufin** [comment]
Documented. Closing.
