### ISSUE TITLE
SELECT statement related dialect functions

### ISSUE THREAD

**Issue by ChengyuanZhao** [GoogleCloudPlatform/google-cloud-spanner-hibernate#8]
override and implement as needed , including but limited to:

- [x] supportsCurrentTimestampSelection
- [x] isCurrentTimestampSelectStringCallable
- [x] getCurrentTimestampSelectString
- [ ] getCurrentTimestampSQLFunctionName (might not need to override)
- [x] buildSQLExceptionConverter (no need to override)
- [ ] buildSQLExceptionConversionDelegate (relies on understanding simba error codes)
- [ ] getViolatedConstraintNameExtracter (relies on understanding simba error codes)
- [x] getSelectClauseNullString (default impl. is correct)
- [x] supportsUnionAll
- [x] createOuterJoinFragment (default impl. is correct)
- [x] createCaseFragment (default impl. is likely correct)
- [x] getNoColumnsInsertString (likely not possible to insert an empty row in Spanner table?)
- [x] getLowercaseFunction (default impl. is correct)
- [ ] getCaseInsensitiveLike (Spanner does not support)
- [x] supportsCaseInsensitiveLike
- [x] transformSelectString (default impl is fine.)
- [x] getMaxAliasLength (default setting is fine.)
- [x] toBooleanValueString
- [ ] registerKeyword (likely no need to override)
- [ ] getKeywords (likely no need to override)
- [ ] buildIdentifierHelper (likely no need to override)
- [ ] openQuote (default setting of **"** seems fine)
- [ ] closeQuote (default setting of **"** seems fine)
- [ ] Quote (default impl should be fine.)

**Comment by ChengyuanZhao** [comment]
assigned via coin flip

**Comment by meltsufin** [comment]
Sounds like there is a missing feature in the Github Assignees module.

**Comment by dzou** [comment]
Went through each method - it appears that most of them should work with their default impls except for maybe a few. PR coming shortly.
