### ISSUE TITLE
Sample application.

### ISSUE THREAD

**Issue by ChengyuanZhao** [GoogleCloudPlatform/google-cloud-spanner-hibernate#80]
Awaiting a driver

**Comment by meltsufin** [comment]
For now, can you just use the jar we use for the tests? We can always swap in the official one.

**Comment by ChengyuanZhao** [comment]
Yes @meltsufin  but for a sample I didn't want to have our mysterious "test-driver.jar" in there.

**Comment by meltsufin** [comment]
I see, well it can remain unmerged into master until fully available. I was just thinking that we shouldn't have to block on it.
