### ISSUE TITLE
Modify PersistentTableBulkIdStrategy to support Spanner DDL syntax

### ISSUE THREAD

**Issue by ChengyuanZhao** [GoogleCloudPlatform/google-cloud-spanner-hibernate#90]
relevant for inheritance hierarchies

**Comment by meltsufin** [comment]
The idea is to see if we can modify it to make it work for us.

**Comment by meltsufin** [comment]
The workaround is documented, but we might be able to create and auto-wire our own version of `PersistentTableBulkIdStrategy`.

**Comment by meltsufin** [comment]
We're now auto-configuring `InlineIdsOrClauseBulkIdStrategy` in our dialect.
Done in #151.
